# Generated by Django 5.2.11 on 2026-03-03 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_resource_link_alter_resource_link_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='icon',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.resource'),
        ),
    ]
