# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounts", "0006_resource_icon_resource_is_menu_resource_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftDeleteMarker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.CharField(max_length=64)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id")},
            },
        ),
        migrations.AddIndex(
            model_name="softdeletemarker",
            index=models.Index(fields=["content_type", "object_id"], name="accounts_sof_content_e0f22c_idx"),
        ),
    ]
