# Generated by Django 6.0.2 on 2026-04-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_resource_soft_delete_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='softdeletemarker',
            new_name='accounts_so_content_008a3c_idx',
            old_name='accounts_sof_content_e0f22c_idx',
        ),
    ]
