# Generated by Django 6.0.2 on 2026-04-11 05:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_accounts_sof_content_e0f22c_idx_accounts_so_content_008a3c_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationReadState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notification_key", models.CharField(max_length=180)),
                ("read_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_read_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "notification_key")},
            },
        ),
        migrations.AddIndex(
            model_name="notificationreadstate",
            index=models.Index(fields=["user", "notification_key"], name="accounts_no_user_id_a58ec5_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationreadstate",
            index=models.Index(fields=["user", "updated_at"], name="accounts_no_user_id_20fd77_idx"),
        ),
    ]
