# Generated by Django 6.0.2 on 2026-04-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notificationreadstate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationreadstate',
            new_name='accounts_no_user_id_b16a13_idx',
            old_name='accounts_no_user_id_a58ec5_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationreadstate',
            new_name='accounts_no_user_id_41daf5_idx',
            old_name='accounts_no_user_id_20fd77_idx',
        ),
    ]
