# Generated by Django 6.0.2 on 2026-04-14 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_accounts_no_user_id_a58ec5_idx_accounts_no_user_id_b16a13_idx_and_more'),
        ('hotel_settings', '0003_reservationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='hotel_settings.hotelsettings'),
        ),
    ]
