# Generated by Django 5.2.17 on 2026-08-15 21:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_finance_center_menu'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('hotel_settings_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Creacion'), ('UPDATE', 'Modificacion'), ('DELETE', 'Eliminacion')], db_index=True, max_length=10)),
                ('entity', models.CharField(db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_label', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['-occurred_at'], name='accounts_au_occurre_110fed_idx'), models.Index(fields=['entity', 'object_id'], name='accounts_au_entity_e5e2a7_idx'), models.Index(fields=['user', '-occurred_at'], name='accounts_au_user_id_9294cf_idx'), models.Index(fields=['hotel_settings_id', '-occurred_at'], name='accounts_au_hotel_s_22b00c_idx')],
            },
        ),
    ]
