# Generated by Django 6.0.2 on 2026-04-07 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('master_data', '0015_alter_masterdata_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotel_settings.hotelsettings')),
                ('item_type', models.ForeignKey(limit_choices_to={'group': 'ITEM_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='items_by_type', to='master_data.masterdata')),
                ('unit_measure', models.ForeignKey(limit_choices_to={'group': 'UNIT_MEASURE'}, on_delete=django.db.models.deletion.PROTECT, related_name='items_by_unit_measure', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'item',
                'ordering': ['-id'],
                'unique_together': {('hotel_settings', 'name'), ('hotel_settings', 'sku')},
            },
        ),
    ]
