# Generated by Django 6.0.2 on 2026-04-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('master_data', '0016_alter_masterdata_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('previous_stock', models.PositiveIntegerField(default=0)),
                ('new_stock', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='inventory.item')),
                ('movement_type', models.ForeignKey(limit_choices_to={'group': 'INVENTORY_MOVEMENT_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_by_type', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'inventory_movement',
                'ordering': ['-id'],
            },
        ),
    ]
