# Generated by Django 6.0.2 on 2026-04-07 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement'),
        ('rooms', '0004_room_type_model_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('minimum_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_inventory_items', to='inventory.item')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_inventory_items', to='rooms.room')),
            ],
            options={
                'db_table': 'room_inventory',
                'ordering': ['-id'],
                'unique_together': {('room', 'item')},
            },
        ),
    ]
