# Generated by Django 6.0.2 on 2026-04-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_roominventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="maximum_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]

