# Generated by Django 6.0.2 on 2026-04-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_item_maximum_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryRestockAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("DRAFT", "Borrador"), ("RESOLVED", "Resuelta")], db_index=True, default="DRAFT", max_length=20)),
                ("reference", models.CharField(db_index=True, max_length=120)),
                ("current_stock", models.PositiveIntegerField(default=0)),
                ("minimum_stock", models.PositiveIntegerField(default=0)),
                ("suggested_quantity", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_alerts",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_restock_alert",
                "ordering": ["-id"],
                "indexes": [models.Index(fields=["item", "status", "is_active"], name="inventory_r_item_id_311a01_idx")],
            },
        ),
    ]
