# Generated by Django 6.0.2 on 2026-03-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_master_data_fk'),
        ('master_data', '0004_alter_masterdata_group'),
        ('rooms', '0003_master_data_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_check_in', models.DateField()),
                ('expected_check_out', models.DateField()),
                ('real_check_in', models.DateTimeField(blank=True, null=True)),
                ('real_check_out', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(limit_choices_to={'group': 'RESERVATION_ORIGIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_by_origin', to='master_data.masterdata')),
                ('status', models.ForeignKey(limit_choices_to={'group': 'RESERVATION_STATUS'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_by_status', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(limit_choices_to={'group': 'PAYMENT_METHOD'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_deposits_by_payment_method', to='master_data.masterdata')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='reservations.reservation')),
                ('status', models.ForeignKey(limit_choices_to={'group': 'RESERVATION_DEPOSIT_STATUS'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_deposits_by_status', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'reservation_deposit',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_plan', models.ForeignKey(blank=True, limit_choices_to={'group': 'MEAL_PLAN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms_by_meal_plan', to='master_data.masterdata')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_detail', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_details', to='rooms.room')),
            ],
            options={
                'db_table': 'reservation_room',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(limit_choices_to={'group': 'DOCUMENT_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_guests_document_type', to='master_data.masterdata')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.reservation')),
            ],
            options={
                'db_table': 'reservation_guest',
                'ordering': ['-id'],
                'unique_together': {('reservation', 'document_type', 'document_number')},
            },
        ),
    ]
