# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservationroom",
            constraint=models.UniqueConstraint(
                fields=("reservation", "room"),
                name="uq_reservation_room_unique",
            ),
        ),
    ]
