# Generated by Django 6.0.2 on 2026-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('reservations', '0002_reservationroom_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='hotel_settings.reservationpolicy'),
        ),
    ]
