# Generated by Django 6.0.2 on 2026-04-07 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_roominventory"),
        ("reservations", "0005_drop_legacy_room_package_columns"),
        ("rooms", "0003_master_data_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationInventoryCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_type", models.CharField(choices=[("CHECK_IN", "Check-in"), ("CHECK_OUT", "Check-out")], max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_inventory_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_checks",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "reservation_inventory_check",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ReservationInventoryCheckLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expected_quantity", models.PositiveIntegerField(default=0)),
                ("reviewed_quantity", models.PositiveIntegerField(default=0)),
                ("difference_quantity", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="reservations.reservationinventorycheck",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_inventory_check_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "reservation_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_check_lines",
                        to="reservations.reservationroom",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_check_lines",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "db_table": "reservation_inventory_check_line",
                "ordering": ["room_id", "item_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="reservationinventorycheck",
            constraint=models.UniqueConstraint(
                fields=("reservation", "check_type"),
                name="uq_reservation_inventory_check_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationinventorycheckline",
            constraint=models.UniqueConstraint(
                fields=("inventory_check", "room", "item"),
                name="uq_reservation_inventory_check_line_unique",
            ),
        ),
    ]
