# Generated by Django 6.0.3 on 2026-04-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('reservations', '0006_reservation_inventory_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotel_settings.hotelsettings'),
        ),
    ]
