# Generated by Django 6.0.3 on 2026-04-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('reservations', '0008_backfill_reservation_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hotel_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotel_settings.hotelsettings'),
        ),
    ]
