# Generated by Django 6.0.2 on 2026-03-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_typer',
            new_name='room_type',
        ),
    ]
