# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


def migrate_room_catalogs(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")
    Rate = apps.get_model("rooms", "Rate")
    Room = apps.get_model("rooms", "Room")
    MaintenanceOrder = apps.get_model("rooms", "MaintenanceOrder")
    CleaningTask = apps.get_model("rooms", "CleaningTask")

    room_type_id_map = {}
    for item in MasterData.objects.filter(group="ROOM_TYPE"):
        metadata = item.metadata or {}
        legacy_room_type_id = metadata.get("legacy_room_type_id")
        if legacy_room_type_id is None:
            continue
        room_type_id_map[int(legacy_room_type_id)] = item.id

    def group_map(group):
        return {
            item.code: item.id
            for item in MasterData.objects.filter(group=group)
        }

    room_status_map = group_map("ROOM_STATUS")
    maintenance_priority_map = group_map("MAINTENANCE_PRIORITY")
    maintenance_status_map = group_map("MAINTENANCE_STATUS")
    cleaning_task_type_map = group_map("CLEANING_TASK_TYPE")
    cleaning_status_map = group_map("CLEANING_STATUS")

    fallback_room_type_id = next(iter(room_type_id_map.values()), None)
    default_room_status_id = room_status_map.get("DISPONIBLE")
    default_maintenance_priority_id = maintenance_priority_map.get("MEDIA")
    default_maintenance_status_id = maintenance_status_map.get("PENDIENTE")
    default_cleaning_task_type_id = cleaning_task_type_map.get("DIARIA")
    default_cleaning_status_id = cleaning_status_map.get("PENDIENTE")

    rate_updates = []
    for rate in Rate.objects.all().iterator():
        rate.room_type_master_id = room_type_id_map.get(rate.room_type_id) or fallback_room_type_id
        rate_updates.append(rate)

    if rate_updates:
        Rate.objects.bulk_update(rate_updates, ["room_type_master_id"])

    room_updates = []
    for room in Room.objects.all().iterator():
        status_code = (room.status or "").strip().upper()
        room.room_type_master_id = room_type_id_map.get(room.room_type_id)
        room.status_master_id = room_status_map.get(status_code) or default_room_status_id
        room_updates.append(room)

    if room_updates:
        Room.objects.bulk_update(room_updates, ["room_type_master_id", "status_master_id"])

    maintenance_updates = []
    for order in MaintenanceOrder.objects.all().iterator():
        priority_code = (order.priority or "").strip().upper()
        status_code = (order.status or "").strip().upper()

        order.priority_master_id = (
            maintenance_priority_map.get(priority_code) or default_maintenance_priority_id
        )
        order.status_master_id = (
            maintenance_status_map.get(status_code) or default_maintenance_status_id
        )
        maintenance_updates.append(order)

    if maintenance_updates:
        MaintenanceOrder.objects.bulk_update(
            maintenance_updates,
            ["priority_master_id", "status_master_id"],
        )

    cleaning_updates = []
    for task in CleaningTask.objects.all().iterator():
        task_type_code = (task.task_type or "").strip().upper()
        status_code = (task.status or "").strip().upper()

        task.task_type_master_id = (
            cleaning_task_type_map.get(task_type_code) or default_cleaning_task_type_id
        )
        task.status_master_id = (
            cleaning_status_map.get(status_code) or default_cleaning_status_id
        )
        cleaning_updates.append(task)

    if cleaning_updates:
        CleaningTask.objects.bulk_update(
            cleaning_updates,
            ["task_type_master_id", "status_master_id"],
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_rename_room_typer_room_room_type"),
        ("master_data", "0002_seed_master_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="room_type_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "ROOM_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates_tmp",
                to="master_data.masterdata",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "ROOM_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms_tmp",
                to="master_data.masterdata",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="status_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "ROOM_STATUS"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms_by_status_tmp",
                to="master_data.masterdata",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceorder",
            name="priority_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "MAINTENANCE_PRIORITY"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_orders_by_priority_tmp",
                to="master_data.masterdata",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceorder",
            name="status_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "MAINTENANCE_STATUS"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_orders_by_status_tmp",
                to="master_data.masterdata",
            ),
        ),
        migrations.AddField(
            model_name="cleaningtask",
            name="task_type_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "CLEANING_TASK_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cleaning_tasks_by_type_tmp",
                to="master_data.masterdata",
            ),
        ),
        migrations.AddField(
            model_name="cleaningtask",
            name="status_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "CLEANING_STATUS"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cleaning_tasks_by_status_tmp",
                to="master_data.masterdata",
            ),
        ),
        migrations.RunPython(migrate_room_catalogs, noop_reverse),
        migrations.RemoveField(
            model_name="rate",
            name="room_type",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_type",
        ),
        migrations.RemoveField(
            model_name="room",
            name="status",
        ),
        migrations.RemoveField(
            model_name="maintenanceorder",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="maintenanceorder",
            name="status",
        ),
        migrations.RemoveField(
            model_name="cleaningtask",
            name="task_type",
        ),
        migrations.RemoveField(
            model_name="cleaningtask",
            name="status",
        ),
        migrations.RenameField(
            model_name="rate",
            old_name="room_type_master",
            new_name="room_type",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="room_type_master",
            new_name="room_type",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="status_master",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="maintenanceorder",
            old_name="priority_master",
            new_name="priority",
        ),
        migrations.RenameField(
            model_name="maintenanceorder",
            old_name="status_master",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="cleaningtask",
            old_name="task_type_master",
            new_name="task_type",
        ),
        migrations.RenameField(
            model_name="cleaningtask",
            old_name="status_master",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="rate",
            name="room_type",
            field=models.ForeignKey(
                limit_choices_to={"group": "ROOM_TYPE"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="master_data.masterdata",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "ROOM_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="master_data.masterdata",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"group": "ROOM_STATUS"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms_by_status",
                to="master_data.masterdata",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceorder",
            name="priority",
            field=models.ForeignKey(
                limit_choices_to={"group": "MAINTENANCE_PRIORITY"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_orders_by_priority",
                to="master_data.masterdata",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceorder",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"group": "MAINTENANCE_STATUS"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_orders_by_status",
                to="master_data.masterdata",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="task_type",
            field=models.ForeignKey(
                limit_choices_to={"group": "CLEANING_TASK_TYPE"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cleaning_tasks_by_type",
                to="master_data.masterdata",
            ),
        ),
        migrations.AlterField(
            model_name="cleaningtask",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"group": "CLEANING_STATUS"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cleaning_tasks_by_status",
                to="master_data.masterdata",
            ),
        ),
        migrations.DeleteModel(
            name="RoomType",
        ),
    ]
