# Generated by Codex

import django.db.models.deletion
from django.db import migrations, models


def migrate_room_types_from_master_data(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")
    RoomType = apps.get_model("rooms", "RoomType")
    Room = apps.get_model("rooms", "Room")
    Rate = apps.get_model("rooms", "Rate")

    source_items = list(
        MasterData.objects.filter(group="ROOM_TYPE").order_by("sort_order", "id")
    )

    created_ids = set()
    for item in source_items:
        RoomType.objects.update_or_create(
            id=item.id,
            defaults={
                "code": (item.code or "").strip().upper() or f"ROOM_TYPE_{item.id}",
                "name": item.name,
                "description": item.description,
                "capacity": 1,
                "bed_count": 1,
                "bed_type": None,
                "is_active": item.is_active,
                "sort_order": item.sort_order,
                "created_at": item.created_at,
                "updated_at": item.updated_at,
            },
        )
        created_ids.add(item.id)

    referenced_ids = set(
        Room.objects.exclude(room_type_id__isnull=True).values_list("room_type_id", flat=True)
    )
    referenced_ids.update(
        Rate.objects.exclude(room_type_id__isnull=True).values_list("room_type_id", flat=True)
    )

    missing_ids = sorted(referenced_ids - created_ids)
    for room_type_id in missing_ids:
        RoomType.objects.update_or_create(
            id=room_type_id,
            defaults={
                "code": f"LEGACY_{room_type_id}",
                "name": f"Tipo legado {room_type_id}",
                "description": "Migrado automaticamente desde referencias existentes.",
                "capacity": 1,
                "bed_count": 1,
                "bed_type": None,
                "is_active": True,
                "sort_order": 999,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_master_data_fk"),
        ("master_data", "0013_alter_masterdata_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("bed_count", models.PositiveIntegerField(default=1)),
                ("bed_type", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "room_type",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RunPython(migrate_room_types_from_master_data, noop_reverse),
        migrations.AlterField(
            model_name="rate",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="rooms.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="rooms.roomtype",
            ),
        ),
    ]
