# Generated by Django 6.0.3 on 2026-04-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_seed_payment_refund_statuses'),
        ('rooms', '0005_maintenance_order_estimated_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='priority',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'MAINTENANCE_PRIORITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_tasks_by_priority', to='master_data.masterdata'),
        ),
    ]
