# Generated by Django 6.0.3 on 2026-04-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('rooms', '0006_cleaningtask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='hotel_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='hotel_settings.hotelsettings'),
        ),
        migrations.AddField(
            model_name='rate',
            name='hotel_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='hotel_settings.hotelsettings'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='hotel_settings.hotelsettings'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='code',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('hotel_settings', 'name'), name='uq_amenity_hotel_name'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel_settings', 'code'), name='uq_room_type_hotel_code'),
        ),
    ]
