# Generated by Django 6.0.3 on 2026-04-16 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('rooms', '0008_backfill_roomtype_amenity_rate_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='hotel_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='hotel_settings.hotelsettings'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='hotel_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='hotel_settings.hotelsettings'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='hotel_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='hotel_settings.hotelsettings'),
        ),
    ]
