# Generated by Django 5.2.17 on 2026-08-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0007_payment_method_type_and_account'),
        ('master_data', '0020_seed_invoice_reconciliation_statuses'),
        ('rooms', '0012_room_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CLEANING', 'Limpieza'), ('MAINTENANCE', 'Mantenimiento')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], max_length=20)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('next_run_on', models.DateField(db_index=True)),
                ('last_generated_on', models.DateField(blank=True, null=True)),
                ('generated_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_work', to='hotel_settings.hotelsettings')),
                ('priority', models.ForeignKey(blank=True, limit_choices_to={'group': 'MAINTENANCE_PRIORITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_work_by_priority', to='master_data.masterdata')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_work', to='rooms.room')),
                ('task_type', models.ForeignKey(blank=True, limit_choices_to={'group': 'CLEANING_TASK_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_work_by_task_type', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'recurring_work',
                'ordering': ['next_run_on', 'id'],
            },
        ),
    ]
