# Generated by Django 6.1 on 2026-10-10 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_roomtype_rate_billing_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cleaning_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
