# Generated by Codex

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("hotel_settings", "0003_reservationpolicy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("RESERVATION", "Reservation"),
                            ("ROOM", "Room"),
                            ("CLEANING", "Cleaning"),
                            ("MAINTENANCE", "Maintenance"),
                            ("PAYMENT", "Payment"),
                            ("INVOICE", "Invoice"),
                            ("INVENTORY", "Inventory"),
                            ("USER", "User"),
                            ("FINANCE", "Finance"),
                            ("REPORT", "Report"),
                            ("SYSTEM", "System"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("action_url", models.CharField(blank=True, max_length=255, null=True)),
                ("related_object_id", models.CharField(blank=True, max_length=64, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hotel_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="hotel_settings.hotelsettings",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="notif_user_read_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["hotel_settings", "notification_type", "priority"],
                name="notif_hotel_type_prio_idx",
            ),
        ),
    ]
