# Generated by Django 6.0.2 on 2026-04-04 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('master_data', '0007_alter_masterdata_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotel_settings.hotelsettings')),
                ('service_type', models.ForeignKey(limit_choices_to={'group': 'SERVICE_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='services_by_type', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['-id'],
                'unique_together': {('hotel_settings', 'name')},
            },
        ),
    ]
