# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MasterData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("DOCUMENT_TYPE", "Document type"),
                            ("CLIENT_TYPE", "Client type"),
                            ("CLIENT_STATUS", "Client status"),
                            ("ROOM_TYPE", "Room type"),
                            ("ROOM_STATUS", "Room status"),
                            ("MAINTENANCE_PRIORITY", "Maintenance priority"),
                            ("MAINTENANCE_STATUS", "Maintenance status"),
                            ("CLEANING_TASK_TYPE", "Cleaning task type"),
                            ("CLEANING_STATUS", "Cleaning status"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "master_data",
                "ordering": ["group", "sort_order", "name"],
                "unique_together": {("group", "code")},
            },
        ),
    ]
