# Generated by Codex

from django.db import migrations
from django.utils.text import slugify


SEED_ROWS = [
    ("DOCUMENT_TYPE", "CC", "Cedula de ciudadania", 1, {}),
    ("DOCUMENT_TYPE", "CE", "Cedula de extranjeria", 2, {}),
    ("DOCUMENT_TYPE", "DNI", "Documento nacional", 3, {}),
    ("DOCUMENT_TYPE", "PASAPORTE", "Pasaporte", 4, {}),

    ("CLIENT_TYPE", "REGULAR", "Regular", 1, {}),
    ("CLIENT_TYPE", "FRECUENTE", "Frecuente", 2, {}),
    ("CLIENT_TYPE", "VIP", "VIP", 3, {}),

    ("CLIENT_STATUS", "ACTIVO", "Activo", 1, {}),
    ("CLIENT_STATUS", "INACTIVO", "Inactivo", 2, {}),
    ("CLIENT_STATUS", "HUESPED_ACTUAL", "Huesped actual", 3, {}),

    ("ROOM_STATUS", "DISPONIBLE", "Disponible", 1, {}),
    ("ROOM_STATUS", "OCUPADA", "Ocupada", 2, {}),
    ("ROOM_STATUS", "MANTENIMIENTO", "Mantenimiento", 3, {}),
    ("ROOM_STATUS", "LIMPIEZA", "Limpieza", 4, {}),
    ("ROOM_STATUS", "FUERA_DE_SERVICIO", "Fuera de servicio", 5, {}),

    ("MAINTENANCE_PRIORITY", "BAJA", "Baja", 1, {}),
    ("MAINTENANCE_PRIORITY", "MEDIA", "Media", 2, {}),
    ("MAINTENANCE_PRIORITY", "ALTA", "Alta", 3, {}),
    ("MAINTENANCE_PRIORITY", "URGENTE", "Urgente", 4, {}),

    ("MAINTENANCE_STATUS", "PENDIENTE", "Pendiente", 1, {}),
    ("MAINTENANCE_STATUS", "EN_PROCESO", "En proceso", 2, {}),
    ("MAINTENANCE_STATUS", "COMPLETADA", "Completada", 3, {}),
    ("MAINTENANCE_STATUS", "CANCELADA", "Cancelada", 4, {}),

    ("CLEANING_TASK_TYPE", "DIARIA", "Diaria", 1, {}),
    ("CLEANING_TASK_TYPE", "SALIDA", "Salida", 2, {}),
    ("CLEANING_TASK_TYPE", "PROFUNDA", "Profunda", 3, {}),
    ("CLEANING_TASK_TYPE", "INSPECCION", "Inspeccion", 4, {}),

    ("CLEANING_STATUS", "PENDIENTE", "Pendiente", 1, {}),
    ("CLEANING_STATUS", "EN_PROCESO", "En proceso", 2, {}),
    ("CLEANING_STATUS", "COMPLETADA", "Completada", 3, {}),
]


def _normalize_room_type_code(name, legacy_id):
    base = slugify(name or "").replace("-", "_").upper()
    if not base:
        base = f"ROOM_TYPE_{legacy_id}"
    return base


def seed_master_data(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")
    connection = schema_editor.connection

    for group, code, name, sort_order, metadata in SEED_ROWS:
        MasterData.objects.update_or_create(
            group=group,
            code=code,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "metadata": metadata,
                "is_active": True,
            },
        )

    table_names = connection.introspection.table_names()
    if "room_type" not in table_names:
        return

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT id, name, description, capacity, bed_count, bed_type, is_active
            FROM room_type
            ORDER BY id
            """
        )
        rows = cursor.fetchall()

    existing_legacy_ids = set()
    for item in MasterData.objects.filter(group="ROOM_TYPE"):
        metadata = item.metadata or {}
        legacy_room_type_id = metadata.get("legacy_room_type_id")
        if legacy_room_type_id is None:
            continue
        existing_legacy_ids.add(int(legacy_room_type_id))

    for row in rows:
        legacy_id, name, description, capacity, bed_count, bed_type, is_active = row
        if int(legacy_id) in existing_legacy_ids:
            continue

        base_code = _normalize_room_type_code(name, legacy_id)
        code = base_code
        suffix = 2
        while MasterData.objects.filter(group="ROOM_TYPE", code=code).exists():
            code = f"{base_code}_{suffix}"
            suffix += 1

        MasterData.objects.create(
            group="ROOM_TYPE",
            code=code,
            name=name or f"Tipo {legacy_id}",
            description=description,
            is_active=bool(is_active),
            sort_order=legacy_id,
            metadata={
                "capacity": int(capacity or 1),
                "bed_count": int(bed_count or 1),
                "bed_type": bed_type,
                "legacy_room_type_id": int(legacy_id),
            },
        )
        existing_legacy_ids.add(int(legacy_id))


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0001_initial"),
        ("clients", "0002_alter_client_client_type_alter_client_status"),
        ("rooms", "0002_rename_room_typer_room_room_type"),
    ]

    operations = [
        migrations.RunPython(seed_master_data, noop_reverse),
    ]
