# Generated by Django 6.0.2 on 2026-03-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_seed_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
            ],
            options={
                'verbose_name': 'Room type',
                'verbose_name_plural': 'Room types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master_data.masterdata',),
        ),
    ]
