# Generated by Codex

from django.db import migrations


SEED_ROWS = [
    ("ROOM_STATUS", "DISPONIBLE", "Disponible", 1, {}),
    ("ROOM_STATUS", "RESERVADA", "Reservada", 2, {}),
    ("ROOM_STATUS", "OCUPADA", "Ocupada", 3, {}),
    ("ROOM_STATUS", "MANTENIMIENTO", "Mantenimiento", 4, {}),
    ("ROOM_STATUS", "LIMPIEZA", "Limpieza", 5, {}),
    ("ROOM_STATUS", "FUERA_DE_SERVICIO", "Fuera de servicio", 6, {}),

    ("RESERVATION_STATUS", "PENDIENTE", "Pendiente", 1, {}),
    ("RESERVATION_STATUS", "CONFIRMADA", "Confirmada", 2, {}),
    ("RESERVATION_STATUS", "EN_CURSO", "En curso", 3, {}),
    ("RESERVATION_STATUS", "FINALIZADA", "Finalizada", 4, {}),
    ("RESERVATION_STATUS", "CANCELADA", "Cancelada", 5, {}),

    ("RESERVATION_ORIGIN", "RECEPCION", "Recepcion", 1, {}),
    ("RESERVATION_ORIGIN", "WEB", "Web", 2, {}),
    ("RESERVATION_ORIGIN", "TELEFONO", "Telefono", 3, {}),
    ("RESERVATION_ORIGIN", "AGENCIA", "Agencia", 4, {}),

    ("MEAL_PLAN", "SOLO_HOSPEDAJE", "Solo hospedaje", 1, {}),
    ("MEAL_PLAN", "DESAYUNO", "Desayuno", 2, {}),
    ("MEAL_PLAN", "MEDIA_PENSION", "Media pension", 3, {}),
    ("MEAL_PLAN", "PENSION_COMPLETA", "Pension completa", 4, {}),
    ("MEAL_PLAN", "TODO_INCLUIDO", "Todo incluido", 5, {}),

    ("PAYMENT_METHOD", "EFECTIVO", "Efectivo", 1, {}),
    ("PAYMENT_METHOD", "TARJETA", "Tarjeta", 2, {}),
    ("PAYMENT_METHOD", "TRANSFERENCIA", "Transferencia", 3, {}),
    ("PAYMENT_METHOD", "PSE", "PSE", 4, {}),

    ("RESERVATION_DEPOSIT_STATUS", "PENDIENTE", "Pendiente", 1, {}),
    ("RESERVATION_DEPOSIT_STATUS", "VALIDADO", "Validado", 2, {}),
    ("RESERVATION_DEPOSIT_STATUS", "RECHAZADO", "Rechazado", 3, {}),
]


def seed_catalogs(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")

    for group, code, name, sort_order, metadata in SEED_ROWS:
        MasterData.objects.update_or_create(
            group=group,
            code=code,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "metadata": metadata,
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0004_alter_masterdata_group"),
    ]

    operations = [
        migrations.RunPython(seed_catalogs, noop_reverse),
    ]
