# Generated by Codex

from django.db import migrations


SEED_ROWS = [
    ("CHARGE_TYPE", "HABITACION", "Habitacion", 1, {}),
    ("CHARGE_TYPE", "PAQUETE", "Paquete", 2, {}),
    ("CHARGE_TYPE", "SERVICIO", "Servicio", 3, {}),
    ("CHARGE_TYPE", "OTRO", "Otro", 4, {}),
]


def seed_charge_types(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")

    for group, code, name, sort_order, metadata in SEED_ROWS:
        MasterData.objects.update_or_create(
            group=group,
            code=code,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "metadata": metadata,
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0008_alter_masterdata_group"),
    ]

    operations = [
        migrations.RunPython(seed_charge_types, noop_reverse),
    ]
