# Generated by Codex

from django.db import migrations


SEED_ROWS = [
    ("INVOICE_STATUS", "BORRADOR", "Borrador", 1),
    ("INVOICE_STATUS", "EMITIDA", "Emitida", 2),
    ("INVOICE_STATUS", "PAGADA", "Pagada", 3),
    ("INVOICE_STATUS", "ANULADA", "Anulada", 4),
]


def seed_invoice_statuses(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")

    for group, code, name, sort_order in SEED_ROWS:
        MasterData.objects.update_or_create(
            group=group,
            code=code,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0010_remove_masterdata_metadata_alter_masterdata_group"),
    ]

    operations = [
        migrations.RunPython(seed_invoice_statuses, noop_reverse),
    ]
