# Generated by Codex

from django.db import migrations


def delete_room_type_master_data(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")
    MasterData.objects.filter(group="ROOM_TYPE").delete()


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0013_alter_masterdata_group"),
        ("rooms", "0004_room_type_model_fk"),
        ("packages", "0002_package_room_type_to_rooms"),
    ]

    operations = [
        migrations.RunPython(delete_room_type_master_data, noop_reverse),
    ]
