# Generated by Django 6.0.2 on 2026-04-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_alter_masterdata_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='group',
            field=models.CharField(choices=[('DOCUMENT_TYPE', 'Document type'), ('CLIENT_TYPE', 'Client type'), ('CLIENT_STATUS', 'Client status'), ('ROOM_TYPE', 'Room type'), ('ROOM_STATUS', 'Room status'), ('MAINTENANCE_PRIORITY', 'Maintenance priority'), ('MAINTENANCE_STATUS', 'Maintenance status'), ('CLEANING_TASK_TYPE', 'Cleaning task type'), ('CLEANING_STATUS', 'Cleaning status'), ('RESERVATION_STATUS', 'Reservation status'), ('RESERVATION_ORIGIN', 'Reservation origin'), ('MEAL_PLAN', 'Meal plan'), ('PAYMENT_METHOD', 'Payment method'), ('RESERVATION_DEPOSIT_STATUS', 'Reservation deposit status'), ('RESERVATION_POLICY_TYPE', 'Reservation policy type'), ('RESERVATION_PENALTY_TYPE', 'Reservation penalty type'), ('SERVICE_TYPE', 'Service type'), ('CHARGE_TYPE', 'Charge type'), ('INVOICE_STATUS', 'Invoice status'), ('CREDIT_NOTE_STATUS', 'Credit note status'), ('PROMOTION_DISCOUNT_TYPE', 'Promotion discount type'), ('ITEM_TYPE', 'Item type'), ('UNIT_MEASURE', 'Unit measure'), ('INVENTORY_MOVEMENT_TYPE', 'Inventory movement type')], db_index=True, max_length=60),
        ),
    ]
