# Generated by Codex

from django.db import migrations


SEED_ROWS = [
    ("PAYMENT_REFUND_STATUS", "PENDIENTE", "Pendiente", 1),
    ("PAYMENT_REFUND_STATUS", "APROBADO", "Aprobado", 2),
    ("PAYMENT_REFUND_STATUS", "PROCESADO", "Procesado", 3),
    ("PAYMENT_REFUND_STATUS", "RECHAZADO", "Rechazado", 4),
    ("PAYMENT_REFUND_STATUS", "ANULADO", "Anulado", 5),
]


def seed_payment_refund_statuses(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")

    for group, code, name, sort_order in SEED_ROWS:
        MasterData.objects.update_or_create(
            group=group,
            code=code,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0018_alter_masterdata_group"),
    ]

    operations = [
        migrations.RunPython(seed_payment_refund_statuses, noop_reverse),
    ]
