# Generated by Django 6.0.2 on 2026-04-04 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('master_data', '0007_alter_masterdata_group'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='hotel_settings.hotelsettings')),
                ('room_type', models.ForeignKey(blank=True, limit_choices_to={'group': 'ROOM_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages_by_room_type', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'package',
                'ordering': ['-id'],
                'unique_together': {('hotel_settings', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='packages.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_packages', to='services.service')),
            ],
            options={
                'db_table': 'package_service',
                'ordering': ['id'],
                'unique_together': {('package', 'service')},
            },
        ),
    ]
