# Generated by Codex

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0001_initial"),
        ("rooms", "0004_room_type_model_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages_by_room_type",
                to="rooms.roomtype",
            ),
        ),
    ]
