# Generated by Django 6.0.2 on 2026-04-05 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0008_alter_masterdata_group'),
        ('packages', '0001_initial'),
        ('reservations', '0005_drop_legacy_room_package_columns'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('charge_type', models.ForeignKey(limit_choices_to={'group': 'CHARGE_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='charges_by_type', to='master_data.masterdata')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='packages.package')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='reservations.reservation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='services.service')),
            ],
            options={
                'db_table': 'charge',
                'ordering': ['-id'],
            },
        ),
    ]
