# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="automation_key",
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="charge",
            name="is_automatic",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
