# Generated by Django 6.0.2 on 2026-04-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_charge_automation_fields'),
        ('master_data', '0010_remove_masterdata_metadata_alter_masterdata_group'),
        ('reservations', '0005_drop_legacy_room_package_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reservations.reservation')),
                ('status', models.ForeignKey(limit_choices_to={'group': 'INVOICE_STATUS'}, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_by_status', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_links', to='billing.charge')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_charges', to='billing.invoice')),
            ],
            options={
                'db_table': 'invoice_charge',
                'ordering': ['id'],
                'unique_together': {('invoice', 'charge')},
            },
        ),
    ]
