# Generated by Django 6.0.2 on 2026-04-06 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment'),
        ('master_data', '0012_alter_masterdata_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='billing.invoice')),
                ('status', models.ForeignKey(limit_choices_to={'group': 'CREDIT_NOTE_STATUS'}, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_by_status', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'credit_note',
                'ordering': ['-id'],
            },
        ),
    ]
