# Generated by Django 6.0.2 on 2026-04-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_creditnote"),
        ("master_data", "0018_alter_masterdata_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                ("refund_date", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="billing.payment",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        limit_choices_to={"group": "PAYMENT_REFUND_STATUS"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_refunds_by_status",
                        to="master_data.masterdata",
                    ),
                ),
            ],
            options={
                "db_table": "payment_refund",
                "ordering": ["-id"],
            },
        ),
    ]
