# Generated by Django 6.0.2 on 2026-04-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('master_data', '0017_alter_masterdata_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(limit_choices_to={'group': 'EXPENSE_CATEGORY'}, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_by_category', to='master_data.masterdata')),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='hotel_settings.hotelsettings')),
                ('payment_method', models.ForeignKey(blank=True, limit_choices_to={'group': 'PAYMENT_METHOD'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_by_payment_method', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'expense',
                'ordering': ['-id'],
            },
        ),
    ]
