# Generated by Codex

import decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialControlConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("district_name", models.CharField(default="Riohacha", max_length=120)),
                ("tourism_law_enabled", models.BooleanField(default=True)),
                (
                    "tourism_law_preferential_rate",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("9.00"), max_digits=5),
                ),
                (
                    "standard_income_tax_rate",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("35.00"), max_digits=5),
                ),
                ("has_iva_exemption", models.BooleanField(default=False)),
                ("iva_rate", models.DecimalField(decimal_places=2, default=decimal.Decimal("19.00"), max_digits=5)),
                (
                    "ica_rate_per_thousand",
                    models.DecimalField(decimal_places=4, default=decimal.Decimal("9.6600"), max_digits=8),
                ),
                (
                    "fontur_rate_per_thousand",
                    models.DecimalField(decimal_places=4, default=decimal.Decimal("2.5000"), max_digits=8),
                ),
                (
                    "break_even_warning_pct",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("90.00"), max_digits=5),
                ),
                (
                    "break_even_optimal_pct",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("110.00"), max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel_settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_control_config",
                        to="hotel_settings.hotelsettings",
                    ),
                ),
            ],
            options={
                "db_table": "financial_control_config",
                "ordering": ["hotel_settings__hotel_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="FinancialStatementSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_year", models.PositiveIntegerField()),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "01"),
                            (2, "02"),
                            (3, "03"),
                            (4, "04"),
                            (5, "05"),
                            (6, "06"),
                            (7, "07"),
                            (8, "08"),
                            (9, "09"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ],
                        default=12,
                    ),
                ),
                (
                    "cash_and_equivalents",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                ("trade_receivables", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                (
                    "current_financial_assets",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                ("inventories", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("current_assets", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                (
                    "property_plant_equipment",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                (
                    "non_current_financial_assets",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                ("intangibles_other", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                (
                    "non_current_assets",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                ("accounts_payable", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                (
                    "financial_obligations_current",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                ("trade_creditors", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("taxes_payable", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                (
                    "current_liabilities",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                (
                    "financial_obligations_non_current",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                (
                    "non_current_liabilities",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                ("equity_capital", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("equity_reserves", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("equity_surplus", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("retained_earnings", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                (
                    "depreciation_expense",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                ("financial_income", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("financial_expense", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                (
                    "income_tax_expense",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                (
                    "other_income_expense",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                (
                    "other_comprehensive_income",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                (
                    "average_accounts_receivable",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
                ),
                ("net_credit_sales", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_statement_snapshots",
                        to="hotel_settings.hotelsettings",
                    ),
                ),
            ],
            options={
                "db_table": "financial_statement_snapshot",
                "ordering": ["-period_year", "-period_month", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hotel_settings", "period_year", "period_month"),
                        name="uq_financial_snapshot_period",
                    )
                ],
            },
        ),
    ]
