# Generated by Codex

from decimal import Decimal

from django.db import migrations, models


MONEY_ZERO = Decimal("0.00")


def _normalize(value):
    return str(value or "").strip().upper()


def _contains_any(value, tokens):
    normalized = _normalize(value)
    return any(token in normalized for token in tokens)


def forwards(apps, schema_editor):
    Expense = apps.get_model("finance", "Expense")
    FinancialStatementSnapshot = apps.get_model("finance", "FinancialStatementSnapshot")

    for expense in Expense.objects.select_related("expense_category").all():
        category_code = _normalize(getattr(getattr(expense, "expense_category", None), "code", ""))
        expense_type = "ADMIN_EXPENSE"
        if _contains_any(category_code, ["VENTA", "SALES", "COMERCIAL"]):
            expense_type = "SALES_EXPENSE"
        elif _contains_any(category_code, ["COSTO", "COST", "COGS"]):
            expense_type = "OPERATING_COST"

        cost_behavior = "FIXED"
        if _contains_any(category_code, ["VARIABLE", "VARIAB"]):
            cost_behavior = "VARIABLE"

        Expense.objects.filter(id=expense.id).update(
            expense_type=expense_type,
            cost_behavior=cost_behavior,
        )

    for snapshot in FinancialStatementSnapshot.objects.all():
        taxes_payable = snapshot.taxes_payable or MONEY_ZERO
        provision_income_tax = snapshot.provision_income_tax or MONEY_ZERO
        provision_ica = snapshot.provision_ica or MONEY_ZERO
        provision_fontur = snapshot.provision_fontur or MONEY_ZERO
        other_tax_provisions = snapshot.other_tax_provisions or MONEY_ZERO

        if (
            provision_income_tax == MONEY_ZERO
            and provision_ica == MONEY_ZERO
            and provision_fontur == MONEY_ZERO
            and other_tax_provisions == MONEY_ZERO
            and taxes_payable > MONEY_ZERO
        ):
            other_tax_provisions = taxes_payable

        recalculated_taxes_payable = (
            provision_income_tax + provision_ica + provision_fontur + other_tax_provisions
        )
        recalculated_current_assets = (
            (snapshot.cash_and_equivalents or MONEY_ZERO)
            + (snapshot.trade_receivables or MONEY_ZERO)
            + (snapshot.current_financial_assets or MONEY_ZERO)
            + (snapshot.inventories or MONEY_ZERO)
        )
        recalculated_non_current_assets = (
            (snapshot.property_plant_equipment or MONEY_ZERO)
            + (snapshot.non_current_financial_assets or MONEY_ZERO)
            + (snapshot.intangibles_other or MONEY_ZERO)
        )
        recalculated_current_liabilities = (
            (snapshot.accounts_payable or MONEY_ZERO)
            + (snapshot.financial_obligations_current or MONEY_ZERO)
            + (snapshot.trade_creditors or MONEY_ZERO)
            + recalculated_taxes_payable
        )
        recalculated_non_current_liabilities = snapshot.financial_obligations_non_current or MONEY_ZERO

        FinancialStatementSnapshot.objects.filter(id=snapshot.id).update(
            provision_income_tax=provision_income_tax,
            provision_ica=provision_ica,
            provision_fontur=provision_fontur,
            other_tax_provisions=other_tax_provisions,
            taxes_payable=recalculated_taxes_payable,
            current_assets=recalculated_current_assets,
            non_current_assets=recalculated_non_current_assets,
            current_liabilities=recalculated_current_liabilities,
            non_current_liabilities=recalculated_non_current_liabilities,
        )


def backwards(apps, schema_editor):
    Expense = apps.get_model("finance", "Expense")
    FinancialStatementSnapshot = apps.get_model("finance", "FinancialStatementSnapshot")

    Expense.objects.update(
        expense_type="ADMIN_EXPENSE",
        cost_behavior="FIXED",
    )
    FinancialStatementSnapshot.objects.update(
        provision_income_tax=MONEY_ZERO,
        provision_ica=MONEY_ZERO,
        provision_fontur=MONEY_ZERO,
        other_tax_provisions=MONEY_ZERO,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_financial_control_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="cost_behavior",
            field=models.CharField(
                choices=[("FIXED", "Fixed"), ("VARIABLE", "Variable")],
                db_index=True,
                default="FIXED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("OPERATING_COST", "Operating cost"),
                    ("ADMIN_EXPENSE", "Administrative expense"),
                    ("SALES_EXPENSE", "Sales expense"),
                ],
                db_index=True,
                default="ADMIN_EXPENSE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="financialstatementsnapshot",
            name="other_tax_provisions",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="financialstatementsnapshot",
            name="provision_fontur",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="financialstatementsnapshot",
            name="provision_ica",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="financialstatementsnapshot",
            name="provision_income_tax",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.RunPython(forwards, backwards),
    ]
