# Generated by Django 6.0.3 on 2026-04-12 23:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_finance_refactor_structured_classification_and_snapshot_consistency'),
        ('hotel_settings', '0003_reservationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcontrolconfig',
            name='operational_high_occupancy_threshold_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='financialcontrolconfig',
            name='operational_high_refunds_threshold_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='financialcontrolconfig',
            name='operational_low_availability_threshold_rooms',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='financialcontrolconfig',
            name='operational_refund_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='financialcontrolconfig',
            name='operational_revenue_drop_threshold_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='financialcontrolconfig',
            name='operational_revenue_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH_OCCUPANCY', 'High occupancy'), ('LOW_AVAILABILITY', 'Low availability'), ('REVENUE_DROP', 'Revenue drop'), ('HIGH_REFUNDS', 'High refunds')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='WARNING', max_length=15)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=15)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_alerts', to='hotel_settings.hotelsettings')),
            ],
            options={
                'db_table': 'operational_alert',
                'ordering': ['-triggered_at', '-id'],
                'indexes': [models.Index(fields=['hotel_settings', 'status', 'alert_type', 'is_active'], name='operational_hotel_s_cf09fd_idx')],
            },
        ),
    ]
