# Generated by Django 5.2.17 on 2026-09-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_requests', '0004_demo_request_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequestFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('prefix', models.CharField(max_length=10)),
                ('demo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='demo_requests.demorequest')),
            ],
            options={
                'db_table': 'demo_request_floor',
                'ordering': ['floor_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequestRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('bed_count', models.PositiveIntegerField(default=1)),
                ('bed_type', models.CharField(blank=True, default='', max_length=50)),
                ('billing_mode', models.CharField(choices=[('ROOM', 'Habitacion completa'), ('PERSON', 'Por persona')], default='ROOM', max_length=12)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('demo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='demo_requests.demorequest')),
            ],
            options={
                'db_table': 'demo_request_room_type',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequestFloorRoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_groups', to='demo_requests.demorequestfloor')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_groups', to='demo_requests.demorequestroomtype')),
            ],
            options={
                'db_table': 'demo_request_floor_room_group',
                'ordering': ['room_type__sort_order', 'room_type_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='demorequestfloor',
            constraint=models.UniqueConstraint(fields=('demo_request', 'floor_number'), name='uq_demo_req_floor_number'),
        ),
        migrations.AddConstraint(
            model_name='demorequestroomtype',
            constraint=models.UniqueConstraint(fields=('demo_request', 'name'), name='uq_demo_req_room_type_name'),
        ),
        migrations.AddConstraint(
            model_name='demorequestfloorroomgroup',
            constraint=models.UniqueConstraint(fields=('floor', 'room_type'), name='uq_demo_req_floor_room_type'),
        ),
    ]
