# Generated by Django 6.0.2 on 2026-04-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_settings', '0003_reservationpolicy'),
        ('master_data', '0013_alter_masterdata_group'),
        ('packages', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.ForeignKey(limit_choices_to={'group': 'PROMOTION_DISCOUNT_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_by_discount_type', to='master_data.masterdata')),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hotel_settings.hotelsettings')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='packages.package')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='services.service')),
            ],
            options={
                'db_table': 'promotion',
                'ordering': ['-id'],
                'unique_together': {('hotel_settings', 'code'), ('hotel_settings', 'name')},
            },
        ),
    ]
