# Generated by Django 6.1 on 2026-10-08 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payment_created_by'),
        ('promotions', '0001_initial'),
        ('reservations', '0015_alter_reservation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SERVICE', 'Servicio'), ('PACKAGE', 'Paquete'), ('STAY', 'Estadia')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_automatic', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_promotions', to=settings.AUTH_USER_MODEL)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_applications', to='billing.charge')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='promotions.promotion')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_applications', to='reservations.reservation')),
            ],
            options={
                'db_table': 'promotion_application',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('reservation', 'promotion', 'charge'), name='uq_promotion_application_charge'), models.UniqueConstraint(condition=models.Q(('charge__isnull', True)), fields=('reservation', 'promotion'), name='uq_promotion_application_reservation')],
            },
        ),
    ]
