# Generated by Django 6.0.2 on 2026-03-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=40)),
                ('document_number', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('client_type', models.CharField(choices=[('VIP', 'VIP'), ('FREQUENT', 'Frequent'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20)),
                ('total_stay_nights', models.PositiveIntegerField(default=0)),
                ('last_stay', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CURRENT_GUEST', 'Current guest')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['-id'],
            },
        ),
    ]
