# Generated by Django 6.0.2 on 2026-03-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('FRECUENTE', 'Frecuente'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('HUESPED_ACTUAL', 'Huesped Actual')], default='ACTIVO', max_length=20),
        ),
    ]
