# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


def migrate_client_catalogs(apps, schema_editor):
    MasterData = apps.get_model("master_data", "MasterData")
    Client = apps.get_model("clients", "Client")

    def group_map(group):
        return {
            item.code: item.id
            for item in MasterData.objects.filter(group=group)
        }

    document_type_map = group_map("DOCUMENT_TYPE")
    client_type_map = group_map("CLIENT_TYPE")
    status_map = group_map("CLIENT_STATUS")

    default_document_type_id = document_type_map.get("CC")
    default_client_type_id = client_type_map.get("REGULAR")
    default_status_id = status_map.get("ACTIVO")

    updates = []
    for client in Client.objects.all().iterator():
        document_type_code = (client.document_type or "").strip().upper()
        client_type_code = (client.client_type or "").strip().upper()
        status_code = (client.status or "").strip().upper()

        if client_type_code == "FREQUENT":
            client_type_code = "FRECUENTE"

        if status_code == "ACTIVE":
            status_code = "ACTIVO"
        elif status_code == "INACTIVE":
            status_code = "INACTIVO"
        elif status_code == "CURRENT_GUEST":
            status_code = "HUESPED_ACTUAL"

        client.document_type_master_id = document_type_map.get(document_type_code) or default_document_type_id
        client.client_type_master_id = client_type_map.get(client_type_code) or default_client_type_id
        client.status_master_id = status_map.get(status_code) or default_status_id
        updates.append(client)

    if updates:
        Client.objects.bulk_update(
            updates,
            ["document_type_master_id", "client_type_master_id", "status_master_id"],
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_client_type_alter_client_status"),
        ("master_data", "0002_seed_master_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_type_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "CLIENT_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients_type",
                to="master_data.masterdata",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="document_type_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "DOCUMENT_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients_document_type",
                to="master_data.masterdata",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="status_master",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"group": "CLIENT_STATUS"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients_status",
                to="master_data.masterdata",
            ),
        ),
        migrations.RunPython(migrate_client_catalogs, noop_reverse),
        migrations.RemoveField(
            model_name="client",
            name="client_type",
        ),
        migrations.RemoveField(
            model_name="client",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="client",
            name="status",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="client_type_master",
            new_name="client_type",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="document_type_master",
            new_name="document_type",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="status_master",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="client",
            name="client_type",
            field=models.ForeignKey(
                limit_choices_to={"group": "CLIENT_TYPE"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients_type",
                to="master_data.masterdata",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="document_type",
            field=models.ForeignKey(
                limit_choices_to={"group": "DOCUMENT_TYPE"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients_document_type",
                to="master_data.masterdata",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"group": "CLIENT_STATUS"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients_status",
                to="master_data.masterdata",
            ),
        ),
    ]
