# Generated by Django 6.0.2 on 2026-04-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_master_data_fk'),
        ('hotel_settings', '0003_reservationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hotel_settings',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='clients',
                to='hotel_settings.hotelsettings',
            ),
        ),
    ]