# Generated by Django 6.0.2 on 2026-04-14 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_backfill_client_hotel'),
        ('hotel_settings', '0003_reservationpolicy'),
        ('master_data', '0020_seed_invoice_reconciliation_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='hotel_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='hotel_settings.hotelsettings'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('hotel_settings', 'document_number'), name='uq_client_hotel_document_number'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), ('email__isnull', False)), fields=('hotel_settings', 'email'), name='uq_client_hotel_email'),
        ),
    ]
