# Generated by Django 6.1 on 2026-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_document_number_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type_is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
