# Generated by Django 6.0.2 on 2026-03-07 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelsettings',
            old_name='email',
            new_name='general_email',
        ),
        migrations.RenameField(
            model_name='hotelsettings',
            old_name='phone',
            new_name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='rooms_per_floor',
        ),
        migrations.RemoveField(
            model_name='hotelsettings',
            name='total_floors',
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='currency',
            field=models.CharField(default='COP', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='facebook',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='instagram',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='legal_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='max_guests_per_room',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='reservations_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='slogan',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='stars',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='system_language',
            field=models.CharField(default='es', max_length=20),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='timezone',
            field=models.CharField(default='America/Bogota', max_length=80),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='twitter_x',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HotelFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('prefix', models.CharField(max_length=10)),
                ('room_count', models.PositiveIntegerField(default=0)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hotel_settings.hotelsettings')),
            ],
            options={
                'db_table': 'hotel_floor',
                'ordering': ['floor_number'],
                'unique_together': {('hotel_settings', 'floor_number')},
            },
        ),
    ]
