# Generated by Django 6.0.2 on 2026-04-02 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0002_rename_email_hotelsettings_general_email_and_more'),
        ('master_data', '0006_alter_masterdata_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('penalty_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('hours_before_checkin', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_policies', to='hotel_settings.hotelsettings')),
                ('penalty_type', models.ForeignKey(limit_choices_to={'group': 'RESERVATION_PENALTY_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_policies_by_penalty_type', to='master_data.masterdata')),
                ('policy_type', models.ForeignKey(limit_choices_to={'group': 'RESERVATION_POLICY_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_policies_by_type', to='master_data.masterdata')),
            ],
            options={
                'db_table': 'reservation_policy',
                'ordering': ['-id'],
                'unique_together': {('hotel_settings', 'name')},
            },
        ),
    ]
