# Generated by Django 5.2.17 on 2026-08-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0004_alter_hotelsettings_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='hotel_settings.hotelsettings')),
            ],
            options={
                'db_table': 'payment_method',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('hotel_settings', 'code'), name='uq_payment_method_hotel_code')],
            },
        ),
    ]
