# Generated by Django 6.1 on 2026-08-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0009_merge_0008_hotelsettings_is_active_0008_hotelsettings_latitude_hotelsettings_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='primary_color',
            field=models.CharField(default='#0f1f41', max_length=7),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='secondary_color',
            field=models.CharField(default='#112853', max_length=7),
        ),
    ]
