# Generated by Django 5.2.7 on 2026-08-21 23:43

import apps.hotel_settings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0011_hotelsettings_reservation_code_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.hotel_settings.models.hotel_photo_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotel_settings.hotelsettings')),
            ],
            options={
                'db_table': 'hotel_photo',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
