# Generated by Django 6.1 on 2026-10-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_settings', '0012_hotelphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='daily_notifications_ran_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
